// Human-edited search snippets. Keep complete thoughts; never truncate at build time.
const descriptions = {
    "ai-accessibility-review-for-customer-service-communications": "Find accessibility barriers in customer messages with AI-assisted review, while keeping human checks and compliance decisions separate.",
    "ai-translation-review-for-service-and-support-teams": "Use AI translation in service and support without hiding uncertainty in technical instructions, customer consent, or everyday communication.",
    "what-to-clean-up-before-ai-touches-your-customer-data-retention-rules": "Define which customer records to keep, archive, and delete before AI makes outdated or unnecessary information easier to retrieve.",
    "what-to-clean-up-before-ai-touches-your-partial-completion-billing-rules": "Clarify partial-completion billing rules before AI screens unfinished service visits for invoicing, approvals, and customer follow-up.",
    "ai-hot-work-permit-readiness-review-commercial-service-teams": "Review hot-work permit readiness with AI before cutting, brazing, or torch work. Keep safety decisions and site authorization with qualified people.",
    "what-to-clean-up-before-ai-touches-your-customer-requested-technician-rules": "Define customer-requested technician rules before AI makes dispatch promises. Clarify preferences, availability, and who can approve exceptions.",
    "what-to-clean-up-before-ai-touches-your-permit-required-scheduling-rules": "Clarify permit requirements and approval ownership before AI schedules work that is not ready for dispatch.",
    "what-to-clean-up-before-ai-touches-your-landlord-vs-tenant-approval-rules": "Set landlord and tenant approval rules before AI routes service requests, estimates, and follow-up work to the wrong decision-maker.",
    "what-to-clean-up-before-ai-touches-your-weather-delay-communication-rules": "Define weather-delay communication rules before AI reschedules service visits or makes new promises to customers.",
    "what-to-clean-up-before-ai-touches-your-customer-key-control-rules": "Clarify customer key-control rules before AI coordinates site entry, after-hours access, and lockup handoffs for service teams.",
    "what-to-clean-up-before-ai-touches-your-cancellation-fee-waiver-rules": "Define cancellation-fee waiver rules before AI screens missed appointments. Make exception criteria and approval ownership explicit.",
    "what-to-clean-up-before-ai-touches-your-tax-exempt-billing-rules": "Clarify tax-exempt billing records and approval rules before AI drafts invoices, intake replies, and billing handoffs.",
    "what-to-clean-up-before-ai-touches-your-after-hours-escalation-roster": "Clean up after-hours escalation rosters before AI routes urgent requests. Define coverage, backup contacts, and handoff ownership.",
    "what-to-clean-up-before-ai-touches-your-reschedule-reason-codes": "Standardize reschedule reason codes before AI routes follow-up or reports on schedule quality. Separate causes, ownership, and next steps.",
    "what-to-clean-up-before-ai-touches-your-customer-portal-submission-rules": "Clarify customer portal submission rules before AI drafts official account updates, closeout notes, and billing documentation.",
    "what-to-clean-up-before-ai-touches-your-customer-supplied-parts-rules": "Define customer-supplied parts rules before AI screens job readiness, responsibility, and approval requirements for service visits.",
    "what-to-clean-up-before-ai-touches-your-special-order-deposit-rules": "Clarify special-order deposit rules before AI moves quoted work into purchasing, approvals, and customer follow-up.",
    "what-to-clean-up-before-ai-touches-your-customer-po-rules": "Define customer purchase-order rules before AI screens dispatch readiness, spending approvals, and invoice release.",
    "what-to-clean-up-before-ai-touches-your-customer-shutdown-windows": "Clarify customer shutdown windows before AI schedules outage work. Define access, approval ownership, and scheduling constraints.",
    "ai-branch-to-branch-parts-transfer-review-service-teams": "Use AI to review branch-to-branch parts transfers before unclear ownership disrupts urgent jobs, inventory records, and office coordination.",
    "what-to-clean-up-before-ai-touches-your-closed-job-reopen-reasons": "Define closed-job reopen reasons before AI routes comeback work, paperwork follow-up, and unresolved service issues.",
    "what-to-clean-up-before-ai-touches-your-service-agreement-coverage-rules": "Clarify service-agreement coverage before AI screens included work, billable exceptions, and cases requiring manager approval.",
    "ai-recall-and-advisory-intake-triage-service-support-teams": "Use AI to triage recall and service-advisory intake while keeping field decisions, billing, and customer communication under review.",
    "what-to-clean-up-before-ai-touches-your-overtime-approval-rules": "Define overtime approval rules before AI screens urgent jobs, premium labor, and customer exceptions for service teams.",
    "what-to-clean-up-before-ai-touches-your-field-safety-escalation-notes": "Clarify field safety escalation notes before AI routes hazards, stop-work reports, and approval follow-up to responsible people.",
    "ai-refrigerant-log-review-commercial-service-teams": "Use AI to flag incomplete refrigerant records for human review before gaps create billing friction, repeat visits, or compliance questions.",
    "what-to-clean-up-before-ai-touches-your-customer-record-merge-rules": "Set duplicate customer record rules before AI routes requests and follow-up using the wrong account history.",
    "what-to-clean-up-before-ai-touches-your-technician-debrief-notes": "Clean up technician debrief notes before AI turns field updates into summaries, customer messages, and follow-up tasks.",
    "why-supervisor-interrupt-load-is-the-ai-metric-to-watch": "Judge operational AI by supervisor interrupts and exception cleanup, not polished replies. Learn what to measure before expanding a rollout.",
    "ai-knowledge-article-freshness-review-support-teams": "Use AI to flag stale support knowledge for review before outdated guidance causes callbacks, rework, and inconsistent answers.",
    "what-to-clean-up-before-ai-touches-your-rebill-risk-queue": "Clean up rebill risk signals before AI flags service jobs for invoice disputes, write-downs, or billing review.",
    "ai-customer-billing-instruction-review-service-support-teams": "Use AI to check customer-specific billing instructions before mismatches delay invoices or create avoidable office cleanup.",
    "ai-recurring-service-scope-creep-review-commercial-service-teams": "Use AI to spot recurring-service scope creep before small exceptions create margin loss, schedule delays, and unclear customer expectations.",
    "ai-customer-portal-update-review-national-account-service-teams": "Review national-account customer portal updates with AI to flag gaps that can delay billing, trigger escalations, and duplicate office work.",
    "ai-maintenance-deficiency-bundling-review-commercial-service-teams": "Use AI to group maintenance findings into clearer next steps, helping teams review priorities, quotes, and approval requests.",
    "ai-no-fault-found-review-service-teams": "Review no-fault-found closeouts with AI before unclear notes lead to repeat dispatches, billing friction, and customer distrust.",
    "ai-maintenance-deferral-review-recurring-service-teams": "Use AI to flag risky maintenance deferrals for review before delays create repeat failures and harder scheduling problems.",
    "ai-planned-outage-review-commercial-service-teams": "Use AI to review planned-outage risks before shutdowns create customer confusion, overtime, and avoidable return visits.",
    "ai-account-mapping-review-multi-location-service-teams": "Use AI to flag customer-account mapping errors before the wrong site, bill-to details, or approval path creates rework.",
};

const learningPaths = [
    { title: "Support triage and handoffs", slug: "support", posts: ["response-time", "automation-small-business", "why-supervisor-interrupt-load-is-the-ai-metric-to-watch"] },
    { title: "Service intake and coordination", slug: "service", posts: ["after-hours-ai-intake", "ai-warranty-claim-intake-for-service-teams", "what-to-clean-up-before-ai-touches-your-customer-po-rules"] },
    { title: "Safe AI deployment", slug: "deployment", posts: ["why-ai-pilots-stall", "age-of-ai-agents", "stay-human"] },
];

module.exports = { descriptions, learningPaths };
